import os
import re
import json
import time
from datetime import datetime
from typing import List

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from pydantic import BaseModel, ValidationError, field_validator


MODEL_ID = "meta-llama/Llama-3.1-8B-Instruct"
# MODEL_ID = "mistralai/Mistral-7B-Instruct-v0.3"


PROMPT = """
You are a safety engineer.

Create an FMEA for the given system.

Return ONLY valid JSON.
Do not return markdown.
Do not return explanations.
Do not return any text before or after the JSON.

SYSTEM DESCRIPTION:
An hydraulic pick-and-place robot has been investigated for reliability using FTA and FMEA. The robot system considered consists of five joints, each driven and controlled by an hydraulic servo-mechanism. Pressure is generated by a conventional motor and pump assembly. Hydraulic fluid is pumped from the reservoir through a filter and a check valve, which ensures flow in one direction. Pressure is kept below the maximum allowable value by means of an unloading valve, usually factory preset. An accumulator is used to assist the pump in supplying additional fluid under a high flow demand. The motion of each hydraulic actuator, which is controlled by a servo-valve, is transmitted to the appropriate limb of the robot either directly or by some mechanical transmission (rods, chains, gears, etc.). Each limb is coupled to a position transducer, in this case an absolute optical encoder, giving the joint angle codes. A multiplexer allows scanning of each code in turn. In playback mode the code for each joint is compared with a corresponding code from the memory giving the joint angle for a previously taught point. A digital difference is converted into an analogue signal according to a pre-specified motion control algorithm. After amplification the signal is applied to the appropriate servo-valve. In teach mode the motion of the arm is controlled by the operator using a teach pendant. When a specific point is to be recorded, the codes from the joint encoders are entered into the memory sequentially. An end-effector, usually a two jaw gripper or a weld gun, is used. For the purposes of this example, a pneumatically operated gripper was considered. Apart from the teach pendant the operator interface consists of a control panel and an emergency stop facility.

COMPONENT LIST:
- Pump
- Filter
- Unload valve
- Check valve
- Pressure gauge
- Relief valves
- Accumulator bladder
- Dump valve
- Servo-valves
- Actuators
- Piping and seals
- Reservoir
- Heat exchanger

REQUIREMENTS:
- Use only the components from the component list.
- Include exactly 25 rows.
- Each row must contain one realistic failure mode.
- Keep each field concise but specific.

OUTPUT FORMAT:
{
  "rows": [
    {
      "component": "...",
      "failure_mode": "...",
      "effect_on_other_components": "...",
      "effect_on_whole_system": "...",
      "detection_method": "...",
      "compensating_provisions_and_remarks": "..."
    }
  ]
}
""".strip()


VALID_COMPONENTS = {
    "pump": "Pump",
    "filter": "Filter",
    "unload valve": "Unload valve",
    "unloading valve": "Unload valve",
    "check valve": "Check valve",
    "pressure gauge": "Pressure gauge",
    "relief valves": "Relief valves",
    "relief valve": "Relief valves",
    "accumulator bladder": "Accumulator bladder",
    "accumulator": "Accumulator bladder",
    "dump valve": "Dump valve",
    "servo-valves": "Servo-valves",
    "servo valves": "Servo-valves",
    "servo-valve": "Servo-valves",
    "servo valve": "Servo-valves",
    "actuators": "Actuators",
    "actuator": "Actuators",
    "piping and seals": "Piping and seals",
    "pipes and seals": "Piping and seals",
    "reservoir": "Reservoir",
    "heat exchanger": "Heat exchanger",
    "heat exchange": "Heat exchanger",
}

ALLOWED_COMPONENTS = set(VALID_COMPONENTS.values())


def normalize_component_name(name: str) -> str:
    cleaned = name.strip()
    cleaned = re.sub(r"^\d+\.\s*", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned)
    return VALID_COMPONENTS.get(cleaned.lower(), cleaned)


class FMEARow(BaseModel):
    component: str
    failure_mode: str
    effect_on_other_components: str
    effect_on_whole_system: str
    detection_method: str
    compensating_provisions_and_remarks: str

    @field_validator("component")
    @classmethod
    def validate_component(cls, v: str) -> str:
        norm = normalize_component_name(v)
        if norm not in ALLOWED_COMPONENTS:
            raise ValueError(f"Invalid component: {v}")
        return norm

    @field_validator(
        "failure_mode",
        "effect_on_other_components",
        "effect_on_whole_system",
        "detection_method",
        "compensating_provisions_and_remarks",
    )
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("Field cannot be empty.")
        return v


class FMEAOutput(BaseModel):
    rows: List[FMEARow]

    @field_validator("rows")
    @classmethod
    def validate_rows_count(cls, v: List[FMEARow]) -> List[FMEARow]:
        if len(v) != 25:
            raise ValueError(f"Expected exactly 25 rows, got {len(v)}")
        return v


def extract_json_block(text: str) -> str:
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("No valid JSON object found in model output.")
    return text[start:end + 1].strip()


def build_chat_input(tokenizer, prompt: str) -> str:
    messages = [{"role": "user", "content": prompt}]
    try:
        return tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
    except Exception:
        return f"<s>[INST] {prompt} [/INST]"


def save_text(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def main() -> None:
    os.makedirs("runs", exist_ok=True)
    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")

    prompt_path = f"runs/{run_id}_prompt.txt"
    raw_path = f"runs/{run_id}_raw.txt"
    json_path = f"runs/{run_id}_output.json"
    perf_path = f"runs/{run_id}_performance.json"
    error_path = f"runs/{run_id}_error.txt"

    print("Loading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=False)

    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    print("Loading model...")
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        torch_dtype=torch.float16,
        device_map="auto",
    )

    print("Preparing input...")
    input_text = build_chat_input(tokenizer, PROMPT)
    inputs = tokenizer(input_text, return_tensors="pt").to(model.device)

    input_tokens = int(inputs["input_ids"].shape[1])

    print("Generating structured FMEA output...")
    start_time = time.time()

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=4000,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
        )

    end_time = time.time()
    generation_time = end_time - start_time

    gen_tokens = output[0][inputs["input_ids"].shape[1]:]
    gen_text = tokenizer.decode(gen_tokens, skip_special_tokens=True).strip()

    output_tokens = int(gen_tokens.shape[0])
    total_tokens = int(input_tokens + output_tokens)

    save_text(prompt_path, PROMPT)
    save_text(raw_path, gen_text)

    print("\n===== RAW MODEL OUTPUT START =====\n")
    print(gen_text[:3000])
    print("\n===== RAW MODEL OUTPUT END =====\n")

    print("\n===== PERFORMANCE METRICS =====")
    print(f"Time taken: {generation_time:.2f} seconds")
    print(f"Input tokens: {input_tokens}")
    print(f"Output tokens: {output_tokens}")
    print(f"Total tokens: {total_tokens}")

    perf_data = {
        "model_id": MODEL_ID,
        "time_seconds": round(generation_time, 2),
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "total_tokens": total_tokens,
    }

    try:
        json_text = extract_json_block(gen_text)
        data = json.loads(json_text)

        if "rows" not in data or not isinstance(data["rows"], list):
            raise ValueError("JSON must contain a top-level 'rows' list.")

        # Keep first 25 rows only if model generates more
        data["rows"] = data["rows"][:25]

        validated = FMEAOutput(**data)

        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(
                {"rows": [row.model_dump() for row in validated.rows]},
                f,
                indent=2,
                ensure_ascii=False,
            )

        with open(perf_path, "w", encoding="utf-8") as f:
            json.dump(perf_data, f, indent=2)

        print("Parsing and validation successful.")
        print(f"Saved {len(validated.rows)} rows.")
        print(f"\nSaved files:\n- {prompt_path}\n- {raw_path}\n- {json_path}\n- {perf_path}")

    except (json.JSONDecodeError, ValidationError, ValueError) as e:
        error_report = f"ERROR:\n{e}\n\nRAW OUTPUT:\n{gen_text}"
        save_text(error_path, error_report)

        with open(perf_path, "w", encoding="utf-8") as f:
            json.dump(perf_data, f, indent=2)

        print("Parsing or validation failed.")
        print(f"Reason: {e}")
        print(f"\nSaved files:\n- {prompt_path}\n- {raw_path}\n- {perf_path}\n- {error_path}")


if __name__ == "__main__":
    main()